sudo: required

services:
  - docker

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_install:
  - docker pull asciidoctor/docker-asciidoctor
  - gem install html-proofer

script:
  # compile the headers
  - gcc headers/fmi3Functions.h
  # generate the HTML documentation
  - docker run -v $TRAVIS_BUILD_DIR/docs:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -b html5 --failure-level WARN fmi_specification.adoc
  # check the generated HTML
  - htmlproofer ./docs --only-4xx

after_error:
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

# disable email notifications about the outcome of the builds
notifications:
  email: false
