version: 2
jobs:
  build:
    machine: true
    steps:
      # use the github deploy key
      - add_ssh_keys:
          fingerprints:
            - "33:26:15:d0:f2:e8:4f:d7:26:8b:b1:9b:a2:1c:ca:f2"
      - checkout
      - run:
          name: Compile headers
          command: gcc ~/project/headers/fmi3Functions.h
      - run:
          name: Parse XSD schema and validate examples
          command: |
            pip install lxml
            python .circleci/validate_xml.py
      - run:
          name: Generate HTML
          command: docker run -v ~/project/:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor --base-dir /documents/ --backend html5 --failure-level WARN docs/fmi_specification.adoc
      - run:
          name: Validate HTML
          command: docker run -v ~/project/docs/:/documents/ 18fgsa/html-proofer /documents --only-4xx
      - run:
          name: Create archive
          command: |
            cd ~/project
            zip fmi-standard.zip README.adoc CHANGELOG.adoc LICENSE.txt docs/fmi_specification.html docs/fmi-spec.css docs/images/* headers/*.h schema/*.xsd
      - store_artifacts:
          path: ~/project/fmi-standard.zip
      - run:
          name: Push HTML to fmi-standard.org
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
            cd
            git config --global user.email "circleci@fmi-standard"
            git config --global user.name "Circle CI"
            git clone git@github.com:modelica/fmi-standard.org.git
            rsync -a --delete --exclude *.adoc ~/project/docs/ ~/fmi-standard.org/docs/3.0-dev/
            cd fmi-standard.org
            git add docs/3.0-dev
            git commit -m "Update generated specification from fmi-standard (${CIRCLE_SHA1})"
            git push
            fi
