version: 2
jobs:
  validate_files:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y cmake gcc g++ git python3-lxml
      - run:
          name: Validate XML
          command: python3 .circleci/validate_xml.py
      - run:
          name: Lint AsciiDoc files
          command: python3 .circleci/lint_docs.py
          # this script prints non-ascii characters to the console
          environment:
            PYTHONIOENCODING: UTF-8
      - run:
          name: Compile headers
          command: gcc ~/project/headers/fmi3Functions.h
      - run:
          name: Compile code snippets
          command: |
            mkdir build
            cd build
            cmake ../docs/examples
            cmake --build .
            cd ..
  build_spec:
    machine: true
    steps:
      # use the github deploy key
      - add_ssh_keys:
          fingerprints:
            - "33:26:15:d0:f2:e8:4f:d7:26:8b:b1:9b:a2:1c:ca:f2"
      - checkout
      - run:
          name: Pull Submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Generate HTML
          command: |
            [[ $CIRCLE_TAG == v* ]] && REVNUMBER=${CIRCLE_TAG:1} || REVNUMBER=${CIRCLE_SHA1:0:7}
            docker run -v ~/project/:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor --base-dir /documents/ --backend html5 --failure-level WARN --verbose --attribute=revnumber=$REVNUMBER --attribute=revdate=$(date +"%F") docs/index.adoc
      - run:
          name: Generate Layered XCP HTML
          command: docker run -v ~/project/:/documents/ asciidoctor/docker-asciidoctor asciidoctor --base-dir /documents/ --backend html5 --failure-level WARN --verbose docs/X_layered_XCP.adoc
      - run:
          name: Validate HTML
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              docker run -v ~/project/docs/:/documents/ 18fgsa/html-proofer /documents --only-4xx
            fi
          no_output_timeout: 60m
      - run:
          name: Create archive
          command: |
            cd ~/project
            zip fmi-standard.zip README.adoc CHANGELOG.adoc LICENSE.txt docs/index.html docs/X_layered_XCP.html docs/fmi-spec.css docs/images/* docs/images/schema/* headers/*.h schema/*.xsd
      - store_artifacts:
          path: ~/project/fmi-standard.zip
      - run:
          name: Push HTML to fmi-standard.org
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              cd
              git config --global user.email "circleci@fmi-standard"
              git config --global user.name "Circle CI"
              git clone git@github.com:modelica/fmi-standard.org.git
              rsync -a --delete --exclude *.adoc ~/project/docs/ ~/fmi-standard.org/docs/3.0-dev/
              cd fmi-standard.org
              git add docs/3.0-dev
              git commit -m "Update generated specification from fmi-standard (${CIRCLE_SHA1:0:7})" || echo "No changes to commit"
              git push
            fi

workflows:
  version: 2
  validate_and_build:
    jobs:
      - validate_files
          filters:
            tags:
              only: /^v.*/
      - build_spec
          filters:
            tags:
              only: /^v.*/
