version: 2
jobs:
  validate:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install sudo
          command: apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
      - run:
          name: Install GCC
          command: apt-get update && apt-get install -y gcc g++
      - run:
          name: Install lxml
          command: pip install lxml
      - run:
          name: Parse XSD schema and validate XML examples
          command: python .circleci/validate_xml.py
      - run:
          name: Compile headers
          command: gcc ~/project/headers/fmi3Functions.h
      - run:
          name: Install CMake
          command: apt-get update && sudo apt-get install -y cmake
      - run:
          name: Run CMake generator
          command: cmake docs/examples/c-code -Bbuild
      - run:
          name: Build examples
          command: cmake --build build
      - run:
          name: Run examples
          command: ./build/Jacobian
  build:
    machine: true
    steps:
      # use the github deploy key
      - add_ssh_keys:
          fingerprints:
            - "33:26:15:d0:f2:e8:4f:d7:26:8b:b1:9b:a2:1c:ca:f2"
      - checkout
      - run:
          name: Compile and run code examples
          command: |
            mkdir build
            cd build
            cmake ../docs/examples/c-code
            cmake --build . --config Release
            ./Jacobian
            cd ..
      - run:
          name: Generate HTML
          command: docker run -v ~/project/:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor --base-dir /documents/ --backend html5 --failure-level WARN docs/index.adoc
      - run:
          name: Validate HTML
          command: docker run -v ~/project/docs/:/documents/ 18fgsa/html-proofer /documents --only-4xx
      - run:
          name: Create archive
          command: |
            cd ~/project
            zip fmi-standard.zip README.adoc CHANGELOG.adoc LICENSE.txt docs/index.html docs/fmi-spec.css docs/images/* headers/*.h schema/*.xsd
      - store_artifacts:
          path: ~/project/fmi-standard.zip
      - run:
          name: Push HTML to fmi-standard.org
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              cd
              git config --global user.email "circleci@fmi-standard"
              git config --global user.name "Circle CI"
              git clone git@github.com:modelica/fmi-standard.org.git
              rsync -a --delete --exclude *.adoc ~/project/docs/ ~/fmi-standard.org/docs/3.0-dev/
              cd fmi-standard.org
              git add docs/3.0-dev
              git commit -m "Update generated specification from fmi-standard (${CIRCLE_SHA1:0:7})" || echo "No changes to commit"
              git push
            fi
